export const WORLD = { code: 'world', name: 'World' }

export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AX', name: 'Åland Islands' },
  { code: 'AL', name: 'Albania' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BM', name: 'Bermuda' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BR', name: 'Brazil' },
  { code: 'IO', name: 'British Indian Ocean Territory' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CA', name: 'Canada' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CX', name: 'Christmas Island' },
  { code: 'CO', name: 'Colombia' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CW', name: 'Curaçao' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czechia' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'EE', name: 'Estonia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'FK', name: 'Falkland Islands' },
  { code: 'FO', name: 'Faroe Islands' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GR', name: 'Greece' },
  { code: 'GL', name: 'Greenland' },
  { code: 'GU', name: 'Guam' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IM', name: 'Isle of Man' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JP', name: 'Japan' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'XK', name: 'Kosovo' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MO', name: 'Macau' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MQ', name: 'Martinique' },
  { code: 'MX', name: 'Mexico' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'MP', name: 'Northern Mariana Islands' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PS', name: 'Palestine' },
  { code: 'PA', name: 'Panama' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RE', name: 'Réunion' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'PM', name: 'Saint Pierre and Miquelon' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'São Tomé and Príncipe' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'KR', name: 'South Korea' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Türkiye' },
  { code: 'VI', name: 'U.S. Virgin Islands' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VN', name: 'Vietnam' },
]

export function getRegion(value) {
  if (value === WORLD.code) return WORLD
  return COUNTRIES.find((c) => c.code === value) || null
}

export const CONTINENTS = [
  { code: 'AFR', name: 'Africa' },
  { code: 'ASI', name: 'Asia' },
  { code: 'EUR', name: 'Europe' },
  { code: 'NAM', name: 'North America' },
  { code: 'OCE', name: 'Oceania' },
  { code: 'SAM', name: 'South America' },
]

export const COUNTRY_CONTINENT = {
  AF: 'ASI',
  AX: 'EUR',
  AL: 'EUR',
  AS: 'OCE',
  AD: 'EUR',
  AR: 'SAM',
  AU: 'OCE',
  AT: 'EUR',
  BD: 'ASI',
  BY: 'EUR',
  BE: 'EUR',
  BM: 'NAM',
  BT: 'ASI',
  BO: 'SAM',
  BA: 'EUR',
  BW: 'AFR',
  BR: 'SAM',
  IO: 'ASI',
  BG: 'EUR',
  KH: 'ASI',
  CA: 'NAM',
  CL: 'SAM',
  CN: 'ASI',
  CX: 'OCE',
  CO: 'SAM',
  CR: 'NAM',
  HR: 'EUR',
  CW: 'NAM',
  CY: 'EUR',
  CZ: 'EUR',
  DK: 'EUR',
  DO: 'NAM',
  EC: 'SAM',
  EG: 'AFR',
  EE: 'EUR',
  SZ: 'AFR',
  FK: 'SAM',
  FO: 'EUR',
  FI: 'EUR',
  FR: 'EUR',
  GE: 'ASI',
  DE: 'EUR',
  GH: 'AFR',
  GI: 'EUR',
  GR: 'EUR',
  GL: 'NAM',
  GU: 'OCE',
  GT: 'NAM',
  HK: 'ASI',
  HU: 'EUR',
  IS: 'EUR',
  IN: 'ASI',
  ID: 'ASI',
  IQ: 'ASI',
  IE: 'EUR',
  IM: 'EUR',
  IL: 'ASI',
  IT: 'EUR',
  JP: 'ASI',
  JE: 'EUR',
  JO: 'ASI',
  KZ: 'ASI',
  KE: 'AFR',
  XK: 'EUR',
  KG: 'ASI',
  LA: 'ASI',
  LV: 'EUR',
  LB: 'ASI',
  LS: 'AFR',
  LI: 'EUR',
  LT: 'EUR',
  LU: 'EUR',
  MO: 'ASI',
  MG: 'AFR',
  MY: 'ASI',
  ML: 'AFR',
  MT: 'EUR',
  MQ: 'NAM',
  MX: 'NAM',
  MC: 'EUR',
  MN: 'ASI',
  ME: 'EUR',
  NA: 'AFR',
  NP: 'ASI',
  NL: 'EUR',
  NZ: 'OCE',
  NG: 'AFR',
  MK: 'EUR',
  MP: 'OCE',
  NO: 'EUR',
  OM: 'ASI',
  PK: 'ASI',
  PS: 'ASI',
  PA: 'NAM',
  PY: 'SAM',
  PE: 'SAM',
  PH: 'ASI',
  PL: 'EUR',
  PT: 'EUR',
  PR: 'NAM',
  QA: 'ASI',
  RE: 'AFR',
  RO: 'EUR',
  RU: 'EUR',
  RW: 'AFR',
  PM: 'NAM',
  SM: 'EUR',
  ST: 'AFR',
  SN: 'AFR',
  RS: 'EUR',
  SG: 'ASI',
  SK: 'EUR',
  SI: 'EUR',
  ZA: 'AFR',
  KR: 'ASI',
  ES: 'EUR',
  LK: 'ASI',
  SE: 'EUR',
  CH: 'EUR',
  TW: 'ASI',
  TZ: 'AFR',
  TH: 'ASI',
  TN: 'AFR',
  TR: 'ASI',
  VI: 'NAM',
  UG: 'AFR',
  UA: 'EUR',
  AE: 'ASI',
  GB: 'EUR',
  US: 'NAM',
  UY: 'SAM',
  VU: 'OCE',
  VN: 'ASI',
}

export function getContinent(countryCode) {
  const code = COUNTRY_CONTINENT[countryCode]
  return CONTINENTS.find((c) => c.code === code) || null
}

export function getContinentRegion(code) {
  return CONTINENTS.find((c) => c.code === code) || null
}

export function getContinentCountries(continentCode) {
  return COUNTRIES.filter((c) => COUNTRY_CONTINENT[c.code] === continentCode)
}
